# INTRODUÇÃO AO DESEMPACOTAMENTO E TUPLAS
# TUPLAS É IGUAL UMA LISTA, SÓ QUE IMUTÁVEL
# USA O '_' (UNDERLINE) PARA UMA VÁRIAVEL QUE VOCÊ NÃO IRÁ UTILIZAR NO CÓDIGO
nomes = ['Henrique', 'Neymar', 'Junior']
# nomes = tuple(nomes) --> TRANSFORMO A LISTA EM UMA TUPLA
# nomes = list(nomes) --> TRANSFORMO A TUPLA EM UMA LISTA
print(nomes[-1])  # --> ESTOU PRINTANDO O ÚLTIMO NOME
print(nomes)  # --> PRINTANDO A LISTA/TUPLA INTEIRA
